spring:

  jpa:
    database: mysql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop

  profiles:
    include:
      - db
      - key

mybatis:
  mapper-locations: classpath:resources/mapper/**/*.xml
  config-location: classpath:mapper/mapper-config.xml