spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stocklog
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: stocklog
    password: stocklog

  jpa:
    database: mysql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop