server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  datasource:
    password: stocklog
    username: stocklog
    url: jdbc:mysql://localhost:3306/stocklog
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  key: hO27fxnV9dbCFfx0YQp6yCYD7Tvqj2T3Lno91rBoMKj1Jxuh2f
  time: 86400000
